---
title: "Modeling_AJ"
author: "A.J. Imholte"
date: "February 10, 2018"
output: html_document
---

```{r}
library(tidyr)
library(readxl)
ProblemCData <- read_excel("C:/Users/aimho/OneDrive/Documents/COMAP-Modeling-Challenge/ProblemCData.xlsx")
RealData <- spread(ProblemCData, key=MSN, value=Data)
```

```{r}
library(ggplot2)
RealData$GPP <- RealData$REPRB / RealData$TEPRB
RealData$GPC <- RealData$RETCB / RealData$TETCB

gg1 <- ggplot(RealData, aes(x = Year, y = GPC)) +
  geom_line(aes(col = StateCode))
plot(gg1)

gg <- ggplot(RealData, aes(x = Year, y = GPP)) +
  geom_line(aes(col = StateCode))
plot(gg)

gg2 <- ggplot(RealData, aes(x = Year, y = REPRB)) +
  geom_line(aes(col = StateCode))
plot(gg2)

gg3 <- ggplot(RealData, aes(x = Year, y = RETCB)) +
  geom_line(aes(col = StateCode))
plot(gg3)
```

```{r}
# Total Energy Consumption - TETCB

#train <- sample(1:nrow(x), nrow(x)/2)
#test <- (-train)
#y.test <- y[-train]
train <- 1:(nrow(RealData) / 2)
trainingdata <- RealData[train]
testingdata <- RealData[-train]
```

```{r}
#Lasso

# library(glmnet)
# LassoMod <- glmnet(x[train,], y[train], alpha = 1)
# plot(LassoMod)
# LassoMod.pred <- predict(LassoMod, s = 207164, newx = x[-train, ])
# mse <- mean((LassoMod.pred-sample(y.test,20)^2))
```



```{r}
# Lasso Regression with 10k cross-validation

library(glmnet)
x <- model.matrix(GPC ~., RealData)[,-1]
y <- RealData$GPC
train <- sample(1:nrow(x), nrow(x)/2)
y <- sample(y, 120)
test <- (-train)
y.test <- y[test]
y <- sample(y, 120)
lasso.mod <- glmnet(x[train,],y[train],alpha=1)
cv.out <- cv.glmnet(x[train,], y[train], alpha=1, nfolds=3)
plot(cv.out)
bestlam <- cv.out$lambda.min
bestlam
lasso.pred <- predict(lasso.mod,s=bestlam,newx = x[test,])
mean((lasso.pred - y[test])^2)
```
```{r}
out <- glmnet(x,y,alpha=1)
lasso.coef <- predict(out, type = "coefficients", s=bestlam)
lasso.coef
```


```{r}
library(glmnet)
x <- model.matrix(REPRB ~., RealData)[,-1]
y <- RealData$TETCB
train <- sample(1:nrow(x), nrow(x)/2)
y <- sample(y, 120)
test <- (-train)
y.test <- y[test]
y <- sample(y, 120)
lasso.mod <- glmnet(x[train,],y[train],alpha=1)
cv.out <- cv.glmnet(x[train,], y[train], alpha=1, nfolds=60)
plot(cv.out)
bestlam <- cv.out$lambda.min
bestlam
lasso.pred <- predict(lasso.mod,s=bestlam,newx = x[test,])
mse.ridge <- mean((lasso.pred - y[test])^2)
```
```{r}
library(glmnet)
x <- model.matrix(REPRB ~., RealData)[,-1]
y <- RealData$TETCB
train <- sample(1:nrow(x), nrow(x)/2)
y <- sample(y, 120)
test <- (-train)
y.test <- y[test]
y <- sample(y, 120)
lasso.mod <- glmnet(x[train,],y[train],alpha=0)
cv.out <- cv.glmnet(x[train,], y[train], alpha=0, nfolds=60)
plot(cv.out)
bestlam <- cv.out$lambda.min
bestlam
lasso.pred <- predict(lasso.mod,s=bestlam,newx = x[test,], exact = T)
mse.ols <- mean((lasso.pred - y[test])^2)
```



```{r}
out <- glmnet(x,y,alpha=1)
lasso.coef <- predict(out, type = "coefficients", s=bestlam)
lasso.coef
```
```{r}
# A linear model with selected model terms...
lm.mod <- lm(RealData$REPRB ~ RealData$CLHCK + RealData$DKEIB + 
    RealData$ELIMD + RealData$HYICB + RealData$LUACD + RealData$LUICD + 
    RealData$LUTCD + RealData$NUEGV + RealData$NUETV + RealData$P1TCD + 
    RealData$USICB + RealData$WXICV)
summary(lm.mod)

lm.mod2 <- lm(RealData$REPRB ~ RealData$CLHCK + RealData$DKEIB + 
    RealData$ELIMD + RealData$HYICB + RealData$LUACD + RealData$NUEGV + RealData$P1TCD + 
    RealData$USICB + RealData$WXICV)
summary(lm.mod2)

#lm.mod3 <- lm(log(RealData$REPRB) ~ log(RealData$CLHCK) + log(RealData$DKEIB) + log(RealData$ELIMB) + log(RealData$HYICB) +
#                                          log(RealData$LUACD) + log(RealData$NUEGV) + log(RealData$P1TCD) + log(RealData$USICB) + log(RealData$WXICV))

# Fix this later
```
```{r}
varstoremove <- c("ABICP", "ARICP", "ABICP", "ARICP", "ARTCP", "ARTXP", "AVACP", "AVTCP", "AVTXP", "AVTXP", "CCEXP", "CCIMP", 'BMTCB',
                  "CCNIP","CLACP","CLCCP","CLEIP","CLICP","CLKCP","CLOCP","CLPRP","CLRCP","CLTCP","CLTXP","COICP", 'COPRK', "DFCCP",
                  "DFICP", "DFRCP","DFTCP", "DFTXP", "DKEIP", "ELEXP", "ELIMP","ELNIP", 'EMFDB', "EMTCP","ESACP", "ESCCP", "ESICP",
                  "ESRCP", "ESTCP",	"ESTXP", "FNICP",	'FOICP', 'FSICP',	'GEEGP', "GETXV", 'GECCB', 'GEEGB', 'GEEGP', 'GEICB', 'GERCB', 'GETCB', 'GETXB', 'GOCCB', 'GORCB', 'HYCCB', 'HYCCP', 'HYEGB', 'HYEGP','HYICB', 'HYICP', 'HYTCB',	'HYTCP', 'HYTXB', 'HYTXP', 'HYTXV',
                  'JFACP', 'JFTCP', 'JFTXP','JKACP','JKTCP', 'JNACP', 'JNTCP','KSCCP', 'KSICP', 'KSRCP', 'KSTCP',	'KSTXP','LGACP', 'LGCCP', 'LGICP', 'LGRCP', 'LGTCP', 'LGTXP',	'LUACP','LUICP','LUTCD','LUTCP', 'LUTCV',	'LUTXP','MBICP', 'MGACP',	'MGCCP','MGICP','MGTCP', 'MGTXP', 'MSICP', 'NAICP', 'NGACP', 'NGCCP',	'NGEIP', 'NGICP', 'NGLPP', 'NGMPP', 'NGPZP', 'NGRCP',	'NGTCP','NGTXP','NGVHP', 'NUEGP', 'NUETP', 'P1ICP', 'P1TCP', 'P1TXP', 'PAACP', 'PACCP', 'PAEIP', 'PAICP', 'PAPRP', 'PARCP', 'PATCP', 'PATXP', 'PATXV',	'PCCCP', 'PCCB', 'PCEIP','PCICP','PCTCP',	'PLICP','POICP','POTCP','POTXP','PPICP','RFACP','RFCCP','RFEIP','RFICP','RFTCP','RFTXP','SGICP','SNICP','SOEGP','SOEGB','SOHCB', 'SOTCB', 'SOTXB','UOICP',	'USICP', 'WDCCB', 'WDEIB', 'WDICB', 'WDRCB', 'WDRCD', 'WDRCP', 'WDRCV', 'WDRSB', 'WDRXB', 'WWCCB', 'WWCCD', 'WWCCV', 'WWCSB', 'WWCXB', 'WWEIB', 'WWEID', 'WWEIV', 'WWICB', 'WWICD', 'WWICV', 'WWISB', 'WWIXB', 'WWTCB', 'WWTCD', 'WWTCV', 'WWTXB', 'WWTXD', 'WWTXV', 'WSCCB', 'WSEIB', 'WSICB','WXICP','WYEG', 'WYEGB', 'WYEGP', 'WYTCB','REPRB', 'ROPRB', 'CLICV' ,'GPP','GPC', 'PCCCD', 'PCCCB', 'PCCCV', 'NUEGB', 'NUETB', 'NUEGV', 'JNACB', 'JNACP','JNTCB','JNTCP', 'WXICD', 'WXICP', 'WXICV')

cleandata <- data.frame(RealData)
cleandata <- cleandata[ , !names(cleandata) %in% varstoremove]
train <- 1:(nrow(cleandata) / 2)
trainingdata <- cleandata[train,]
testingdata <- cleandata[-train,]
```


```{r}
#Pseodocode
# solution list
# all model list
# r2 list
#For i in range from 1 to max variable count
  #For j in range from 1 to al variables
    #estimate consumption with solution plus one additional variable
    #determine the best model with r2
  #add this model to the model list
  #add the term to the solution so we can start with it next time
```

```{r}
library(plm)
adr2list <- c()
modlist <- c()
vars <- colnames(cleandata)
vars <- vars[-331]
vars[331]
  for(i in 3:length(vars)){
    var <- vars[i]
    #lm.mod <- lm(RETCB ~ get(var), data = cleandata)
    plm.mod <- plm(RETCB ~ MGACB + FFTCB + TETCB + ELNIB + ELISB + NUETV + PATXB + CLICD + NGACD + CLKCV + get(var), data = cleandata, index = c("StateCode", "Year"), model = "within")
    adr2 <- r.squared(plm.mod, dfcor =  TRUE)
    adr2list[i] <- adr2
    modlist[i] <- plm.mod
  }
r2max <- which.max(adr2list)
adr2list[r2max]
var <- vars[r2max]
var
```
```{r}
modeldatayears <- subset(cleandata, Year >= 1970)
plm.1 <- plm(RETCB ~ MGACB, data = cleandata, index = c("StateCode", "Year"), model = "within")
plm.2 <- plm(RETCB ~ MGACB + FFTCB, data = cleandata, index = c("StateCode", "Year"), model = "within")
plm.3 <- plm(RETCB ~ MGACB + FFTCB + TETCB, data = cleandata, index = c("StateCode", "Year"), model = "within")
plm.4 <- plm(RETCB ~ MGACB + FFTCB + TETCB + ELNIB, data = cleandata, index = c("StateCode", "Year"), model = "within")
plm.5 <- plm(RETCB ~ MGACB + FFTCB + TETCB + ELNIB + ELISB, data = cleandata, index = c("StateCode", "Year"), model = "within")
plm.6 <- plm(RETCB ~ MGACB + FFTCB + TETCB + ELNIB + ELISB + NUETV, data = cleandata, index = c("StateCode", "Year"), model = "within")
plm.7 <- plm(RETCB ~ MGACB + FFTCB + TETCB + ELNIB + ELISB + NUETV + PATXB, data = cleandata, index = c("StateCode", "Year"), model = "within")
plm.8 <- plm(RETCB ~ MGACB + FFTCB + TETCB + ELNIB + ELISB + NUETV + PATXB + CLICD, data = cleandata, index = c("StateCode", "Year"), model = "within")
plm.9 <- plm(RETCB ~ MGACB + FFTCB + TETCB + ELNIB + ELISB + NUETV + PATXB + CLICD + NGACD , data = cleandata, index = c("StateCode", "Year"), model = "within")
plm.10 <- plm(RETCB ~ MGACB + FFTCB + TETCB + ELNIB + ELISB + NUETV + PATXB + CLICD + NGACD + CLKCV, data = cleandata, index = c("StateCode", "Year"), model = "within")
summary(plm.1)
summary(plm.2)
summary(plm.3)
summary(plm.4)
summary(plm.5)
summary(plm.6)
summary(plm.7)
summary(plm.8)
summary(plm.9)
summary(plm.10)
coefs <- plm.10$coefficients
elasticities = c(coefs[1] * (mean(modeldatayears$MGACB)/mean(modeldatayears$RETCB)), coefs[2] * (mean(modeldatayears$FFTCB)/mean(modeldatayears$RETCB)), coefs[3] * (mean(modeldatayears$TETCB)/mean(modeldatayears$RETCB)), coefs[4] * (mean(modeldatayears$ELNIB)/mean(modeldatayears$RETCB)), coefs[5] * (mean(modeldatayears$ELISB)/mean(modeldatayears$RETCB)), coefs[6] * (mean(modeldatayears$NUETV)/mean(modeldatayears$RETCB)), coefs[7] * (mean(modeldatayears$PATXB)/mean(modeldatayears$RETCB)), coefs[8] * (mean(modeldatayears$CLICD)/mean(modeldatayears$RETCB)),coefs[9] * (mean(modeldatayears$NGACD)/mean(modeldatayears$RETCB)), coefs[10] * (mean(modeldatayears$CLKCV)/mean(modeldatayears$RETCB)))
```


```{r}
Cp <- function(RSS, resid, n) {
  return((1 / n) * (RSS + 2 * var(resid)^2))
}
cplist <- c(Cp(6.9252e+11, plm.1$residuals, 200), Cp(5.3631e+11, plm.2$residuals, 200), Cp(4.2249e+11, plm.3$residuals, 200),
            Cp(3.0887e+11, plm.5$residuals, 200), Cp(1.1184e+11, plm.6$residuals, 160), Cp(8.5299e+10, plm.7$residuals, 160),
            Cp(7.4283e+10, plm.8$residuals, 160), Cp(6.9246e+10, plm.9$residuals, 160), Cp(6.3984e+10, plm.10$residuals, 160))
rsqlist <- c(r.squared(plm.1, dfcor = TRUE), r.squared(plm.2, dfcor = TRUE), r.squared(plm.3, dfcor = TRUE),
             r.squared(plm.4, dfcor = TRUE), r.squared(plm.5, dfcor = TRUE), r.squared(plm.6, dfcor = TRUE),
             r.squared(plm.7, dfcor = TRUE), r.squared(plm.8, dfcor = TRUE), r.squared(plm.9, dfcor = TRUE),
             r.squared(plm.10, dfcor = TRUE))
numbervars <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
par(mfrow = c(1,2))
plot(rsqlist, ylab = "Adjusted R Squared", xlab = "Number of Variables", type = "o")
plot(cplist, ylab = "Cp", xlab = "Number of Variables", type = "o")
```
```{r}
library(stats)
library(forecast)
modeldataAZ <- subset(modeldatayears, StateCode == "AZ")
modeldataCA <- subset(modeldatayears, StateCode == "CA")
modeldataNM <- subset(modeldatayears, StateCode == "NM")
modeldataTX <- subset(modeldatayears, StateCode == "TX")
tsAZ <- ts(modeldataAZ, frequency = 1, start = 1970)
tsCA <- ts(modeldataCA, frequency = 1, start = 1970)
tsNM <- ts(modeldataNM, frequency = 1, start = 1970)
tsTX <- ts(modeldataTX, frequency = 1, start = 1970)
AZlm <- lm(RETCB ~ MGACB + FFTCB + TETCB + ELNIB + ELISB + 
    NUETV + PATXB + CLICD + NGACD + CLKCV, data = tsAZ)
CAlm <- lm(RETCB ~ MGACB + FFTCB + TETCB + ELNIB + ELISB + 
    NUETV + PATXB + CLICD + NGACD + CLKCV, data = tsCA)
NMlm <- lm(RETCB ~ MGACB + FFTCB + TETCB + ELNIB + ELISB + 
    NUETV + PATXB + CLICD + NGACD + CLKCV, data = tsNM)
TXlm <- lm(RETCB ~ MGACB + FFTCB + TETCB + ELNIB + ELISB + 
    NUETV + PATXB + CLICD + NGACD + CLKCV, data = tsTX)
```
```{r}
elasticities
coefsAZ <- AZlm$coefficients
elasticitiesAZ = c(coefsAZ[2] * (mean(modeldataAZ$MGACB)/mean(modeldataAZ$RETCB)), coefsAZ[3] * (mean(modeldataAZ$FFTCB)/mean(modeldataAZ$RETCB)), coefsAZ[4] * (mean(modeldataAZ$TETCB)/mean(modeldataAZ$RETCB)), coefsAZ[5] * (mean(modeldataAZ$ELNIB)/mean(modeldataAZ$RETCB)), coefsAZ[6] * (mean(modeldataAZ$ELISB)/mean(modeldataAZ$RETCB)), coefsAZ[7] * (mean(modeldataAZ$NUETV)/mean(modeldataAZ$RETCB)), coefsAZ[8] * (mean(modeldataAZ$PATXB)/mean(modeldataAZ$RETCB)), coefsAZ[9] * (mean(modeldataAZ$CLICD)/mean(modeldataAZ$RETCB)),coefsAZ[10] * (mean(modeldataAZ$NGACD)/mean(modeldataAZ$RETCB)), coefsAZ[11] * (mean(modeldataAZ$CLKCV)/mean(modeldataAZ$RETCB)))
elasticitiesAZ
coefsCA <- CAlm$coefficients
elasticitiesCA <- c(coefsCA[2] * (mean(modeldataCA$MGACB)/mean(modeldataCA$RETCB)), coefsCA[3] * (mean(modeldataCA$FFTCB)/mean(modeldataCA$RETCB)), coefsCA[4] * (mean(modeldataCA$TETCB)/mean(modeldataCA$RETCB)), coefsCA[5] * (mean(modeldataCA$ELNIB)/mean(modeldataCA$RETCB)), coefsCA[6] * (mean(modeldataCA$ELISB)/mean(modeldataCA$RETCB)), coefsCA[7] * (mean(modeldataCA$NUETV)/mean(modeldataCA$RETCB)), coefsCA[8] * (mean(modeldataCA$PATXB)/mean(modeldataCA$RETCB)), coefsCA[9] * (mean(modeldataCA$CLICD)/mean(modeldataCA$RETCB)),coefsCA[10] * (mean(modeldataCA$NGACD)/mean(modeldataCA$RETCB)), coefsCA[11] * (mean(modeldataCA$CLKCV)/mean(modeldataCA$RETCB)))
elasticitiesCA
coefsNM <- NMlm$coefficients
elasticitiesNM <- c(coefsNM[2] * (mean(modeldataNM$MGACB)/mean(modeldataNM$RETCB)), coefsNM[3] * (mean(modeldataNM$FFTCB)/mean(modeldataNM$RETCB)), coefsNM[4] * (mean(modeldataNM$TETCB)/mean(modeldataNM$RETCB)), coefsNM[5] * (mean(modeldataNM$ELNIB)/mean(modeldataNM$RETCB)), coefsNM[6] * (mean(modeldataNM$ELISB)/mean(modeldataNM$RETCB)), coefsNM[7] * (mean(modeldataNM$NUETV)/mean(modeldataNM$RETCB)), coefsNM[8] * (mean(modeldataNM$PATXB)/mean(modeldataNM$RETCB)), coefsNM[9] * (mean(modeldataNM$CLICD)/mean(modeldataNM$RETCB)),coefsNM[10] * (mean(modeldataNM$NGACD)/mean(modeldataNM$RETCB)), coefsNM[11] * (mean(modeldataNM$CLKCV)/mean(modeldataNM$RETCB)))
elasticitiesNM
coefsTX <- TXlm$coefficients
elasticitiesTX <- c(coefsTX[2] * (mean(modeldataTX$MGACB)/mean(modeldataTX$RETCB)), coefsTX[3] * (mean(modeldataTX$FFTCB)/mean(modeldataTX$RETCB)), coefsTX[4] * (mean(modeldataTX$TETCB)/mean(modeldataTX$RETCB)), coefsTX[5] * (mean(modeldataTX$ELNIB)/mean(modeldataTX$RETCB)), coefsTX[6] * (mean(modeldataTX$ELISB)/mean(modeldataTX$RETCB)), coefsTX[7] * (mean(modeldataTX$NUETV)/mean(modeldataTX$RETCB)), coefsTX[8] * (mean(modeldataTX$PATXB)/mean(modeldataTX$RETCB)), coefsTX[9] * (mean(modeldataTX$CLICD)/mean(modeldataTX$RETCB)),coefsTX[10] * (mean(modeldataTX$NGACD)/mean(modeldataTX$RETCB)), coefsTX[11] * (mean(modeldataTX$CLKCV)/mean(modeldataTX$RETCB)))
elasticitiesTX
```
```{r}
par(mfrow = c(2,2))
plot(modeldataAZ$Year, modeldataAZ$RETCB, pch = 20, main = "AZ Green Energy Consumption", xlab ="Year", ylab = "Consumption (Billions of BTU")
lines(modeldataAZ$Year, AZlm$fitted.values, col = "red")
plot(modeldataCA$Year, modeldataCA$RETCB, pch = 20, main = "CA Green Energy Consumption", xlab ="Year", ylab = "Consumption (Billions of BTU")
lines(modeldataCA$Year, CAlm$fitted.values, col = "red")
plot(modeldataNM$Year, modeldataNM$RETCB, pch = 20, main = "NM Green Energy Consumption", xlab ="Year", ylab = "Consumption (Billions of BTU")
lines(modeldataNM$Year, NMlm$fitted.values, col = "red")
plot(modeldataTX$Year, modeldataTX$RETCB, pch = 20, main = "TX Green Energy Consumption", xlab ="Year", ylab = "Consumption (Billions of BTU")
lines(modeldataTX$Year, TXlm$fitted.values, col = "red")
```

```{r}
elasticities
elasticitiesAZ
elasticitiesCA
elasticitiesNM
elasticitiesTX
```

```{r}
names2 <- c("Motor Gasoline Consumption (Transportation)", "Fossil Fuels Consumption", "Total Energy Consumption", "U.S. Electricity Net Imports", "Net Electricity Interstate Sales", "Nuclear Fuel Expenditure", "Petroleum Product Consumption", "Coal Price (Industrial)", "Natural Gas Price (Transportation)", "Coal Expenditure (Coke Plants)")
elasticiites.df <- data.frame(elasticities, elasticitiesAZ, elasticitiesCA, elasticitiesNM, elasticitiesTX)
elasticiites.df$Total <- elasticiites.df$elasticities
elasticiites.df$Arizona <- elasticiites.df$elasticitiesAZ
elasticiites.df$California <- elasticiites.df$elasticitiesCA
elasticiites.df$NewMexico <- elasticiites.df$elasticitiesNM
elasticiites.df$Texas <- elasticiites.df$elasticitiesTX
elasticiites.df <- elasticiites.df[,5:ncol(elasticiites.df)]
elasticiites.df <- elasticiites.df[,-1]
```

```{r}
library(smooth)
smaRETCB5 <- sma(RealData$RETCB, order = 5)
smaRETCB10 <- sma(RealData$RETCB, order = 10)
smaMGACB5 <- sma(RealData$MGACB, order = 5)
smaMGACB10 <- sma(RealData$MGACB, order = 10)
smaFFTCB5 <- sma(RealData$FFTCB, order = 5)
smaFFTCB10 <- sma(RealData$FFTCB, order = 10)
smaTETCB5 <- sma(RealData$TETCB, order  = 5)
smaTETCB10 <- sma(RealData$TETCB, order = 10)
smaELNIB5 <- sma(RealData$ELNIB, order = 5)
smaELNIB10 <- sma(RealData$ELNIB, order = 10)
smaELISB5 <- sma(RealData$ELISB, order = 5)
smaELISB10 <- sma(RealData$ELISB, order = 10)
smaNUETV5 <- sma(RealData$NUETV, order = 5)
smaNUETV10 <- sma(RealData$NUETV, order = 10)
smaPATXB5 <- sma(RealData$PATXB, order = 5)
smaPATXB10 <- sma(RealData$PATXB, order = 10)
smaCLICD5 <- sma(RealData$CLICD, order = 5)
smaCLICD10 <- sma(RealData$CLICD, order = 10)
smaNGACD5 <- sma(RealData$NGACD, order = 5)
smaNGACD10 <- sma(RealData$NGACD, order = 10)
smaCLKCV5 <- sma(RealData$CLKCV, order = 5)
smaCLCKV10 <- sma(RealData$CLKCV, order = 5)
```

```{r}
retcbmean <- mean(smaRETCB5, smaRETCB10)
mgacbmean <- mean(smaMGACB5, smaMGACB10)
fftcbmean <- mean(smaFFTCB5, smaFFTCB10)
tetcbmean <- mean(smaTETCB5, smaTETCB5)
elnibmean <- mean(smaELNIB5, smaELNIB10)
elisbmean <- mean(smaELISB5, smaELISB10)
nuetvmean <- mean(smaNUETV5, smaNUETV10)
patxbmean <- mean(smaPATXB5, smaPATXB10)
clicdmean <- mean(smaCLICD5, smaCLICD10)
ngacdmean <- mean(smaNGACD5, smaNGACD10)
clkcvmean <- mean(smaCLKCV5, smaCLCKV10)
```


